### ISSUE TITLE
File Open Dialog

### ISSUE THREAD

**Issue by GirkovArpa** [rodrigocfd/winsafe#10]
How to show the file open dialog?

```rust 
let mut foo: winsafe::IUnknown = winsafe::CoCreateInstance(
  &winsafe::shell::clsid::FileOpenDialog,
  None,
  winsafe::co::CLSCTX::INPROC_SERVER,
).unwrap();
````

This code runs without errors but doesn't show a file open dialog.

**Comment by rodrigocfd** [comment]
You need the [IOpenFileDialog](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ifileopendialog) along with something [like this](https://docs.microsoft.com/en-us/windows/win32/learnwin32/example--the-open-dialog-box).

IOpenFileDialog is not supported yet, but I'm working on it right now, so it'll probably out today.

**Comment by rodrigocfd** [comment]
There you go:

```rust
use winsafe::{co, CoCreateInstance, shell};

self.my_button.on().bn_clicked({
    let self2 = self.clone();
    move || {
        let fileo: shell::IFileOpenDialog = CoCreateInstance(
            &shell::clsid::FileOpenDialog,
            None,
            co::CLSCTX::INPROC_SERVER,
        ).unwrap();

        fileo.IFileDialog.SetOptions(
            fileo.IFileDialog.GetOptions().unwrap()
            | co::FOS::FORCEFILESYSTEM | co::FOS::FILEMUSTEXIST,
        ).unwrap();

        fileo.IFileDialog.SetFileTypes(&[
            ("Documents", "*.docx;*.txt"),
            ("Images", "*.jpg;*.png;*.bmp"),
            ("All files", "*.*"),
        ]).unwrap();

        fileo.IFileDialog.SetFileTypeIndex(0).unwrap();

        let user_clicked_ok = fileo.IFileDialog.IModalWindow
            .Show(self2.wnd.hwnd()).unwrap();

        if user_clicked_ok {
            let shi = fileo.IFileDialog.GetResult().unwrap();
            let file_path = shi.GetDisplayName(co::SIGDN::FILESYSPATH).unwrap();
            println!("{}", file_path);
        }
    }
});
```

If this didn't work for you, please reopen the issue.

Please not that I'm still implementing the related interfaces. I just uploaded the bare mininum to make the code above work. There are **a lot** of methods.

Also, I'm not 100% sure of this COM implementation. The way it is, you have to call the base interfaces manually (since Rust has no inheritance). For example: instead of `fileo.SetOptions()`, you must call `fileo.IFileDialog.SetOptions()`. Maybe it's possible to rework it using traits, I'll check that later.

**Comment by GirkovArpa** [comment]
This works perfectly!
