### ISSUE TITLE
WM_MOUSEMOVE for controls?

### ISSUE THREAD

**Issue by GirkovArpa** [rodrigocfd/winsafe#12]
I would like to handle `MOUSEMOVE` for a label, but it doesn't have such an event.  I don't think labels support custom messages like [here](https://rodrigocfd.github.io/winsafe/winsafe/gui/events/struct.WindowEvents.html#examples), right?  

I can't use `self.wnd.on().wm_mouse_move({` because it stops firing when the cursor moves over a control.

**Comment by GirkovArpa** [comment]
I can use [`GetCursorPos`](https://rodrigocfd.github.io/winsafe/winsafe/fn.GetCursorPos.html) in conjunction with [`ScreenToClient`](https://rodrigocfd.github.io/winsafe/winsafe/struct.HWND.html#method.ScreenToClient) inside a loop, actually.

**Comment by rodrigocfd** [comment]
If you want to handle [non-ordinary messages](https://stackoverflow.com/questions/51164396/how-to-detect-hovering-over-a-static-win32-control) in a native control, you must [subclass](https://docs.microsoft.com/en-us/windows/win32/controls/subclassing-overview) it, which is automatically done through [`on_subclass`](https://rodrigocfd.github.io/winsafe/winsafe/gui/struct.Label.html#method.on_subclass) method.

Take care though. Subclassing is very dangerous, because you're messing with the internal message handling of the native control.

**Comment by rodrigocfd** [comment]
I can't test it right now, but it appears to be correct.
