### ISSUE TITLE
EnumPrinters

### ISSUE THREAD

**Issue by ehrw1n** [rodrigocfd/winsafe#142]
Would it be feasible to create a safe wrapper for EnumPrinters, possibly behind a cargo feature, or would WMI be a better alternative for printer enumeration?

**Comment by rodrigocfd** [comment]
As far as I saw, it seems feasible. The API is [horrible](https://learn.microsoft.com/en-us/windows/win32/printdocs/enumprinters) though, do you have an example in C or C++ which I could use as a guide?

**Comment by rodrigocfd** [comment]
`EnumPrinters` is actually an API to various functions, which are accessed though a `Level` parameter. Each `Level` return an array with a different struct. The two most common seem to be:

* `2` – slower, more complete;
* `4` – faster, few info.

The [printers](https://crates.io/crates/printers) crate which you linked only implements `Level` = `2`.

I implemented both, and you can choose according to your needs:

* [`EnumPrinters2`](https://rodrigocfd.github.io/winsafe/winsafe/fn.EnumPrinters2.html); and
* [`EnumPrinters4`](https://rodrigocfd.github.io/winsafe/winsafe/fn.EnumPrinters4.html).

Please let me know if this works for you.

**Comment by rodrigocfd** [comment]
I have no experience with this API, but according to the documentation, the difference is the return type: [`PRINTER_INFO_2`](https://learn.microsoft.com/en-us/windows/win32/printdocs/printer-info-2) (large) vs [`PRINTER_INFO_4`](https://learn.microsoft.com/en-us/windows/win32/printdocs/printer-info-4) (small). In order to fill the larger struct, the OS has to make one call to [`OpenPrinter`](https://learn.microsoft.com/en-us/windows/win32/printdocs/openprinter) for each printer, which makes it an expensive call.
