### ISSUE TITLE
Cannot infer type

### ISSUE THREAD

**Issue by GirkovArpa** [rodrigocfd/winsafe#37]
I know this is probably more of a newbie rustacean issue, but I've tried `match` without any luck:

```rust
let color: winsafe::COLORREF = winsafe::COLORREF::new(0xff, 0x00, 0x00);
let brush: winsafe::HBRUSH = GdiHbrush::CreateSolidBrush(color).unwrap();
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
```

I'm trying to set the main window's background color.

**Comment by GirkovArpa** [comment]
I found the solution in an old respository of mine:
```rust
let color = COLORREF::new(0xff, 0x00, 0x00);
let brush = HBRUSH::CreateSolidBrush(red).unwrap();
```
To change the window background to red:
```rust
let wnd = gui::WindowMain::new(gui::WindowMainOpts {
    class_bg_brush: winsafe::gui::Brush::Handle(brush),
    ..Default::default()
});
```

**Comment by rodrigocfd** [comment]
Actually, you're leaking a GDI resource when doing this, because `CreateSolidBrush` creates a new GDI resource in memory, which should be freed with [`DeleteObject`](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-deleteobject). That's why `CreateSolidBrush` is generally used ony with `WM_PAINT` handling.

If you just want to give the window a background brush, you should use [`HBRUSH::from_sys_color`](https://docs.rs/winsafe/0.0.10/winsafe/prelude/trait.GdiHbrush.html#method.from_sys_color), which will instruct Windows to create and manage a brush for you, what is also slightly faster. Under the hood, what it does is to use a trick of the [`WNDCLASSEX`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-wndclassexw) struct, where you pass the color constant plus 1 to the `hbrBackground` member.

Win32 API has *lots* of tricks.
