### ISSUE TITLE
There's SetClipboardData but not GetClipboardData yet?

### ISSUE THREAD

**Issue by GirkovArpa** [rodrigocfd/winsafe#44]
Also, how does one use `SetClipboardData`?

I tried this:

```rust
    fn events(&self) {
        self.btn_hello.on().bn_clicked({
            let self2 = self.wnd.clone(); // clone so it can be passed into the closure
            move || {
                let mut ptr = b"Hello World\0".to_vec().as_mut_ptr() as *mut u8;
                self2.hwnd().OpenClipboard();
                SetClipboardData(CF::TEXT, ptr);
                CloseClipboard();
```

(modified from https://github.com/rodrigocfd/winsafe-examples/blob/941627b5ea93d7e7e564c91478a88a1d64e2dcf4/01_button_click/src/my_window.rs#L38-L41)

But when I click the button, the program crashes with:

```sh
error: process didn't exit successfully: `target\debug\app.exe` (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)
```

**Comment by rodrigocfd** [comment]
First, I've marked `SetClipboardData` as `unsafe`, because it deals with a raw pointer; `GetClipboardData` is now implemented as well.

I have plans to make safe versions of these two functions, but it's not easy, due to the large amount of possible data that can be stored.

As for the usage, specifically to store text, take a look [here](https://stackoverflow.com/q/1264137/6923555). The memory block must contain a proper Win32 UTF-16 string, which you can easily generate with [`WString`](https://docs.rs/winsafe/0.0.11/winsafe/struct.WString.html). You're trying to store a Rust UTF-8 string, which won't work.
