### ISSUE TITLE
Circular reference via event handlers causes memory leak

### ISSUE THREAD

**Issue by Hawk777** [rodrigocfd/winsafe#52]
I think there is a memory leak in [the `02_combo_and_radios` example](https://github.com/rodrigocfd/winsafe-examples/tree/master/02_combo_and_radios), which might be best addressed in this repo rather than in the example. Remove the `#[derive(Clone)]` from `MyWindow` and implement that and `Drop` by hand, with instrumentation, to see it:

```rust
pub struct MyWindow {
	wnd:        gui::WindowMain,
	cmb_cities: gui::ComboBox,
	rad_seas:   gui::RadioGroup,
}

impl Clone for MyWindow {
	fn clone(&self) -> Self {
		println!("Clone");
		Self {
			wnd: self.wnd.clone(),
			cmb_cities: self.cmb_cities.clone(),
			rad_seas: self.rad_seas.clone(),
		}
	}
}

impl Drop for MyWindow {
	fn drop(&mut self) {
		println!("Drop");
	}
}
```

When you run the code you see “Clone” printed three times (so there are four instances of MyWindow, the one created directly in MyWindow::new and then the three clones captured in event handler closures), but “Drop” is only printed once! So three objects have been leaked. The problem, if I understand correctly, is that there is a circular reference:
1. The `MyWindow` contains a `gui::WindowMain`.
2. The `WindowMain` contains a `RawDlg`, in this case the `RawDlg::Raw` variant.
3. The `RawDlg::Raw` contains a `RawMain`.
4. The `RawMain` contains a `Pin<Arc<Obj>>`.
5. The `Obj` contains a `RawBase`.
6. The `RawBase` contains a `Base`.
7. The `Base` contains a `WindowEventsAll`.
8. The `WindowEventsAll` contains a `FuncStore<(u16, co::NM), Box<dyn Fn(wm::Notify) -> AnyResult<Option<isize>>>`.
9. The `FuncStore` contains a `Vec<Pair>` with one element.
10. The element of the `Vec` contains a `Box`.
11. The `Box` contains a the closure passed to `ComboBoxEvents::cbn_sel_change`.
12. The closure contains a `MyWindow`.

So the `Pin<Arc<Obj>>` in step 4 contains, via a very long chain, a reference to itself.

Application code could fix this if it was very careful: instead of cloning `MyWindow`, it could hold `MyWindow` behind an `Rc` and always downgrade the `Rc` to a `Weak` and capture the `Weak` as part of the closure, upgrading it on each call; thus step 12 would break the cycle (since the closure would only contain a `Weak`). However, this is unintuitive and it would be easy to get it wrong.

I noticed you are only allowed to register event handlers before the `HWND` has been created. I wonder, would it make any sense that, when the `HWND` is *destroyed*, you drop all the event handlers? After all, if the `HWND` has been destroyed, they aren’t needed any more (since no more events can be delivered to them), and dropping them would break the circular reference. Although I’m not sure how well that would work with dynamic creation and destruction of controls, since many event handlers conceptually belong to child windows (e.g. `WM_COMMAND` handlers for buttons) but are actually registered against the parent (since that’s where the `WM_COMMAND` is actually sent).

**Comment by rodrigocfd** [comment]
This is a very interesting problem. Yes, you understanding is correct: there is a circular reference happening though all that chain, which can be summarized as: *window has closures which have window*.

> I noticed you are only allowed to register event handlers before the `HWND` has been created. I wonder, would it make any sense that, when the `HWND` is destroyed, you drop all the event handlers?

Yes, it does make sense, and that's indeed what I implemented. The only caveat is that this dropping – ultimately calling [`Vec::clear`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.clear) to release all closures – must be done after *the very last* possible message to be processed, which according to our much cherished [Raymond Chen](https://devblogs.microsoft.com/oldnewthing/20050726-00/?p=34803) (and my own observations) is `WM_NCDESTROY`. And not just that: the cleanup must happen only after any user-defined `WM_NCDESTROY` have been executed themselves, otherwise they would be lost (with their potential cleanups, leading to leaks). Oh and to make it even more robust, the struct pointer is cleaned *before* the closures cleanup, so any weird messages after `WM_NCDESTROY` won't be handled.

> Although I’m not sure how well that would work with dynamic creation and destruction of controls

Not really a concern – dynamically created controls are not allowed by the library (at least by now), because, as you said, most events belong to the parent window, and handling that scenario has proven to be *extremely complex*. Maybe I'll implement this in the future, but I know it would require a complete rework of the message plumbing.

Your example now runs fine, and I found no side-effects on any of my own programs. Please let me know if this solution works for you.

Thank you very much for your time and effort.

**Comment by Hawk777** [comment]
Everything you said makes sense to me; thank you for all your work on `winsafe`!
