### ISSUE TITLE
how to create a UpDown/Spin control

### ISSUE THREAD

**Issue by Detector-I** [rodrigocfd/winsafe#62]
Hi thank you for the great library, the only problem that I find with it so far is its not so **WINAPI** beginner friendly...
I mean the `gui` feature is good and straight forward, but if you want to use any other feature like for example `comctl` it become so complex...
I mean I can't figure out how can I create a simple **UpDown/Spin control**, checking the original Microsoft documentation wont help either because how winsafe work is kinda different...
overall It will be very good if it were possible to reduce complexity a little...

btw as I said atm I'm trying to create a **UpDown/Spin control** but I can't figure it out, can you please help a little about it?

**Comment by rodrigocfd** [comment]
> the only problem that I find with it so far is its not so **WINAPI** beginner friendly...

WinSafe was never meant to be easier. It's meant to be a Rust binding **safer** than [winapi](https://crates.io/crates/winapi) and [windows](https://crates.io/crates/windows) crates, which are wildly unsafe – basically writing C in Rust.

The problem here is, if you can't write WinAPI code in C, you certainly can't write in Rust either. So, if you're a beginner, I strongly suggest you to study the WinAPI in C. Once you learn the concepts, WinSafe will be a piece of cake for you, because you'll be surrounded by a lot of guardrails.

> I mean the `gui` feature is good and straight forward, but if you want to use any other feature like for example `comctl` it become so complex...

I'm glad you like the `gui` module.

The `gui` module is just a thin layer over the window creation/handling, because it's *very* tedious to write it, and you end up rewriting the same thing over and over again. So I gathered all the stuff together. Plus, lots of corner cases and dirty tricks are properly handled.

> I mean I can't figure out how can I create a simple **UpDown/Spin control**, checking the original Microsoft documentation wont help either because how winsafe work is kinda different...

It is not different at all. If you can create any control in C, you can create it in Rust with WinSafe. [Here](https://github.com/rodrigocfd/winsafe/issues/51) you have an example of how to create a [Tab control](https://learn.microsoft.com/en-us/windows/win32/controls/tab-controls) from scratch.

> overall It will be very good if it were possible to reduce complexity a little...
> 
> btw as I said atm I'm trying to create a **UpDown/Spin control** but I can't figure it out, can you please help a little about it?

As you already noticed, I already implemented [many native controls](https://rodrigocfd.github.io/winsafe/winsafe/gui/index.html) in the `gui` module. I plan to implement **all** of them. I'll take a look at the [UpDown](https://learn.microsoft.com/en-us/windows/win32/controls/up-down-controls), and I'll do my best to add it to the collection. I'll leave this issue open until I get it (soon, I hope).

Thank you for the UpDown control suggestion.

**Comment by Detector-I** [comment]
thank you for fast respond

> WinSafe was never meant to be easier. It's meant to be a Rust binding **safer** than [winapi](https://crates.io/crates/winapi) and [windows](https://crates.io/crates/windows) crates, which are wildly unsafe – basically writing C in Rust.

oh is that so... my first look at winsafe library was `gui` and because it was very easy to start working with I kinda expected to have same experience with other features as well... but looks like not, currently its still same API with a little changes most of the times...
I hope to someday see more good and easy to use codes like what we currently have in `gui`.

> It is not different at all. If you can create any control in C, you can create it in Rust with WinSafe. [Here](https://github.com/rodrigocfd/winsafe/issues/51) you have an example of how to create a [Tab control](https://learn.microsoft.com/en-us/windows/win32/controls/tab-controls) from scratch.

thank you, I checked it and now things are a little more clear to me on how to manually do things... its not as easy, but it get the job done...

At the end thank you for all your works.

**Comment by Detector-I** [comment]
One anther thing I noticed
when a control will be drop? when the parent dropped?
I'm asking because if I make something and it goes out of scoop it wont get deleted, so Im wondering maybe it relay on parent?

and one last thing, why you wrap everything into `Arc`? I mean Im not complaining it make working with them a lot easier but why?

**Comment by rodrigocfd** [comment]
> One anther thing I noticed when a control will be drop? when the parent dropped? I'm asking because if I make something and it goes out of scoop it wont get deleted, so Im wondering maybe it relay on parent?

Usually you'll have your control as a field of the same struct which has the window itself, like:

```rust
pub struct MyWindow {
  wnd: gui::WindowMain,
  btn: gui::Button,
}
```

And then something like:

```rust
fn main() {
  let my_window = MyWindow::new();
  my_window.run_main(None);
}
```

So the control will go out of scope together with `my_window`.

> and one last thing, why you wrap everything into `Arc`? I mean Im not complaining it make working with them a lot easier but why?

Where did you see this?

**Comment by Detector-I** [comment]
> Where did you see this?

I was talking about controls inner data
```rs
pub struct ListView(Pin<Arc<Obj>>);
```
