### ISSUE TITLE
as_mut may be unsound

### ISSUE THREAD

**Issue by Hawk777** [rodrigocfd/winsafe#63]
In commit da6aed76770c0bcc2475d357f023d1912c6979a2 you started using the `as_mut` function in a lot of places, which takes an `&Foo` and turns it into an `&mut Foo`. I am concerned this may be unsound (i.e. invoke undefined behaviour).

First, to quote [the Rustonomicon](https://doc.rust-lang.org/nomicon/transmutes.html):
> Transmuting an `&` to `&mut` is Undefined Behavior. While certain usages may appear safe, note that the Rust optimizer is free to assume that a shared reference won't change through its lifetime and thus such transmutation will run afoul of those assumptions. So:
>
> * Transmuting an `&` to `&mut` is always Undefined Behavior.
> * No you can't do it.
> * No you're not special.

In fact, please see [this example on the Rust playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=cd1ebff2a75777f23f99147c4246ef03) in which I do basically the same thing as your `as_mut` function. Notice that function `f` writes the value 42 into variable `x`, and then function `g` prints it, yet when run in release mode, it prints zero, not 42! (it prints 42 in debug mode). The compiler has clearly observed that `f` is passed an immutable reference to a thing that does not contain an `UnsafeCell`, therefore there is no way `f` could possibly have modified `x`, therefore the call to `g` can assume `x` is zero.

The reason why the code prior to da6aed76770c0bcc2475d357f023d1912c6979a2 was sound is because it used `UnsafeCell`, which is not just a plain wrapper struct; if you look at the `UnsafeCell` source code, it’s a lang-item ([`#[lang = "unsafe_cell"]`](https://doc.rust-lang.org/stable/src/core/cell.rs.html#1925)) which means even if you do exactly the same thing that `UnsafeCell` does in your own code, you won’t get the same result because `UnsafeCell` itself is magic.

**Comment by rodrigocfd** [comment]
You are correct; although I found no problems whatsoever in all the programs I compiled (they all keep working correctly), I missed [that part](https://doc.rust-lang.org/nomicon/transmutes.html) of the Rustonomicon, and that part itself is enough to me to keep me from doing it.

In fact, this is the very same UB we have with C++'s [`const_cast`](https://en.cppreference.com/w/cpp/language/const_cast) – it's probably okay if the variable was originally `mut`, otherwise it's UB. Although my tests showed nothing wrong, I should have suspected the correlation; when it comes to low-level stuff, C++ and Rust often have similar behaviors. Plus, the fact that the conversion cannot be made `const` itself is a strong smell that things are happening under the hood.

Nonetheless your example is very very interesting.

I'll revert this change ASAP. Thank you very much.
