### ISSUE TITLE
Custom color on for class_bg_brush on WindowMainOpts

### ISSUE THREAD

**Issue by nijippoi** [rodrigocfd/winsafe#65]
Hi @rodrigocfd

Thank you for making this crate!
It helped a lot by avoiding typing unsafe blocks all over the place.

I am trying to change the color of the main window to a custom RGB color.
I cannot get the correct instance to pass to class_bg_brush.
Could you please guide me on what I have to do here?

```rust
static BLUE = COLORREF::new(0x0Au8, 0xBAu8, 0xB5u8);
let bg_brush = HBRUSH::CreateSolidBrush(BLUE).unwrap(); // this returns DeleteGuardObject<HBRUSH>, but I want an HBRUSH to pass to below
let class_bg_brush = gui::Brush::Handle(bg_brush);

let wnd = gui::WindowMain::new(
    gui::WindowMainOpts {
        title: "My App".to_owned(),
        size: (400, 400),
        style: WS::CAPTION
            | WS::SYSMENU
            | WS::BORDER
            | WS::SIZEBOX
            | WS::MINIMIZEBOX
            | WS::MAXIMIZEBOX,
        class_bg_brush,
        ..Default::default()
    },
);
```

**Comment by rodrigocfd** [comment]
This happens because the window demands an **owned** background brush – the window itself will delete it, see the `hbrBackground` member of [`WNDCLASSEX`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-wndclassexw).

In C++, `CreateSolidBrush` returns a handle with no safety restrictions, and no concept of ownership. WinSafe adds safety restrictions, with `CreateSolidBrush` returning a guard which will delete the brush automatically. So, Rust won't let you pass this guard to the window, otherwise the brush would be deleted twice.

So, you need to give the brush ownership to the window. Just call [`leak`](https://rodrigocfd.github.io/winsafe/winsafe/guard/struct.DeleteObjectGuard.html#method.leak):

```rust
class_bg_brush: gui::Brush::Handle(
	unsafe {
		HBRUSH::CreateSolidBrush(
			winsafe::COLORREF::new(0x0a, 0xba, 0xb5),
		).unwrap().leak()
	},
),
```
