### ISSUE TITLE
GetTokenInformation missing

### ISSUE THREAD

**Issue by 13-05** [rodrigocfd/winsafe#84]
I'm quite bad at Windows API things (which is the reason I'm using this library), so I don't know the difficulty of implementing this function. My use case is to check whether or not the current program is running with elevated (ie "Admin") privileges, and it seems that [the best way](https://github.com/yandexx/is_elevated/blob/master/src/lib.rs#L56) [to do so](https://stackoverflow.com/questions/8046097/how-to-check-if-a-process-has-the-administrative-rights/8196291#8196291) [requires the GetTokenInformation function](https://users.rust-lang.org/t/how-do-i-determine-if-i-have-admin-rights-on-windows/35710/4).

**Comment by rodrigocfd** [comment]
I implemented an `unsafe` version of [`GetTokenInformation`](https://rodrigocfd.github.io/winsafe/winsafe/prelude/trait.kernel_Haccesstoken.html#method.GetTokenInformation), because the struct to be passed *has* to match the constant. This is the same case of [`SystemParametersInfo`](https://rodrigocfd.github.io/winsafe/winsafe/fn.SystemParametersInfo.html): the safe implementation demands an enum to receive a mutable reference of each possible struct, matched with each possible constant. This is *very* tricky to implement, because some structs have wild pointer operations, something hard to do under Rust strict borrow checker requirements.

I plan to implement this in the future, but for now, this version should suffice for you to use it right away. This code worked for me:

```rust
use winsafe::{self as w, prelude::*, co};

let htoken = w::HPROCESS::GetCurrentProcess()
    .OpenProcessToken(co::TOKEN::QUERY)?;

let mut elevation = w::TOKEN_ELEVATION::default();
unsafe {
    htoken.GetTokenInformation(
        co::TOKEN_INFORMATION_CLASS::Elevation,
        &mut elevation,
    )?;
}
println!("Is elevated: {}", elevation.TokenIsElevated());
```

**Comment by 13-05** [comment]
Thank you!
